version: "3"
services:
  web:
    build: .
    ports:
      - "8010:8010"
      - "9989:9989"
    links:
      - db
  db:
    image: mariadb:10.3
    expose:
      - "3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=eck90542
